name: Add new item to project board

on:
  workflow_call:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: echo "::notice Not adding this item to the board. This should now be handled automatically by the board itself. Delete this job if it is still active in october."
