name: Run npm version and push tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: What version would you like to use?

env:
  NODE_VERSION: lts/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "yarn"
      - run: yarn install --frozen-lockfile --ignore-scripts
      - name: npm version
        run: |
          npm version ${{ github.event.inputs.version }} --ignore-scripts
          git push origin ${{ github.ref_name }}
          git push --tags
        env:
          CI: true
